These are test cases for 1-my_list.py


case 0: import
>>> MyList = __import__('1-my_list').MyList
>>>


case 1: common case

>>> my_list = MyList()
>>> my_list.append(1)
>>> my_list.append(10)
>>> my_list.append(15)
>>> my_list.append(30)
>>> my_list.append(50)
>>> print(my_list)
[1, 10, 15, 30, 50]
>>> print(my_list)
[1, 10, 15, 30, 50]
>>>


case 2: passed a list
>>> a = [20, 40, 30]
>>> my_list = MyList(a)
>>> my_list.print_sorted()
[20, 30, 40]
>>>


case 3: passing empty list
>>> a = []
>>> my_list = MyList(a)
>>> my_list.print_sorted()
[]
>>>


case 4: same number
>>> my_list2 = MyList()
>>> my_list2.append(5)
>>> my_list2.append(5)
>>> my_list2.append(5)
>>> my_list2.print_sorted()
[5, 5, 5]
>>>


case 5: check for negative numbers

>>> MyList = __import__('1-my_list').MyList
>>> my_list = MyList()
>>> my_list.append(-4)
>>> my_list.append(-40)
>>> my_list.append(-400)
>>> my_list.print_sorted()
[-400, -40, -4]
>>>


case 6: not defined object

>>> MyList = __import__('1-my_list').MyList
>>> my_list3.print_sorted()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'my_list2' is not found
>>>
